# Set new leader
unbind C-b
set -g prefix C-a

# Rebind window splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Set default shell
# set-option -g default-shell /etc/zsh

# Use vim bindings
setw -g mode-keys vi

